from datetime import timedelta

MAX_SELECT_OPTION_COUNT = 25
INTERACTION_TIMEOUT = timedelta(minutes=5)
PROVIDER_TIMEOUT = timedelta(seconds=30)
EMBED_FIELD_VALUE_MAX_LENGTH = 1024
SELECT_OPTION_LABEL_MAX_LENGTH = 100
ELEMENT_DESCRIPTION_MAX_LENGTH = 200
